apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pgyap3i44-nodejs
  janus-idp.io/tekton: pgyap3i44-nodejs
  backstage.io/kubernetes-id: pgyap3i44-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pgyap3i44-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
